### PR TITLE
Allow filename in constructor.

### PR DESCRIPTION
**Pull request by alexsegura**
Hello, 

Nice extension, but I struggled to use it in Symfony out of the box. 

With a small change it is now possible to specify the filename in the constructor and also register it as a Symfony service.

### CODE REVIEW

**Comment by m1** [comment]
Looks good! Thanks for the pull req.

**Comment by alexsegura** [comment]
You're welcome. 

Could you make a new release please?

**Comment by m1** [comment]
Yeah was going to do one tonight, just gonna flesh out the README a bit more

**Comment by m1** [comment]
@alexsegura Sorry for the delay, released now :)

**Pull request merged**
